spring.application.name=askthedoc

spring.datasource.url=jdbc:postgresql://localhost:5433/rag_db
spring.datasource.username=postgres
spring.datasource.password=Manoj@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true